import type { Metadata } from "next";
import { ProjectBriefForm } from "@/components/project-brief-form";
import { TIDYCAL_URL } from "@/lib/utils";

export const metadata: Metadata = { title: "Start a Software, Analytics, or AI Project", description: "Send a project brief or book a 15-minute consultation with a U.S.-based senior engineer.", alternates: { canonical: "/book" } };

export default function BookPage() {
  return <div className="pt-16"><section className="max-w-7xl mx-auto px-6 md:px-10"><div className="label-mono">Start a project</div><h1 className="mt-3 text-4xl md:text-6xl font-semibold tracking-tight">Two easy ways to <span className="text-gradient">start with an engineer.</span></h1><p className="mt-5 text-muted text-lg max-w-3xl">Send enough context for a useful response, or choose a 15-minute slot. No automated AI sales sequence and no handoff to someone who cannot answer technical questions.</p></section><section className="max-w-7xl mx-auto px-6 md:px-10 mt-12 grid lg:grid-cols-2 gap-6 items-start"><div className="card p-6 md:p-8"><div className="label-mono">Option 1 / Project brief</div><h2 className="mt-2 text-2xl font-semibold">Describe what you need.</h2><p className="mt-2 text-sm text-muted">Your brief is saved directly to our private Postgres database for personal review.</p><div className="mt-6"><ProjectBriefForm /></div></div><div id="calendar" className="card p-2 overflow-hidden scroll-mt-24"><div className="p-5"><div className="label-mono">Option 2 / Calendar</div><h2 className="mt-2 text-2xl font-semibold">Book 15 minutes.</h2><p className="mt-2 text-sm text-muted">Bring the problem. Leave with a clearer technical path.</p></div><iframe src={TIDYCAL_URL} className="w-full h-[760px] rounded-[12px] bg-white" title="Book a 15-minute consultation" /><p className="p-4 text-xs font-mono text-muted text-center">Calendar not loading? <a href={TIDYCAL_URL} target="_blank" rel="noreferrer" className="text-accent">Open it directly ↗</a></p></div></section></div>;
}
